[general]
# apiEndpoint = "https://c12312loud.backend.ai"
apiEndpointText = "webui"
# defaultSessionEnvironment=cr.backend.ai/cloud/python-tensorflow
# defaultSessionEnvironment = "cr.backend.ai/multiarch/python"
# defaultSessionEnvironment = "cr.backend.ai/cloud/python"
# defaultSessionEnvironment = "cr.backend.ai/testing/ngc-pytorch"
defaultSessionEnvironment = "cr.backend.ai/testing/ngc-pytorch"
# siteDescription = "AI Infra Server"
# connectionMode = "SESSION"
allowChangeSigninMode = false
signupSupport = true
allowSignout = true
allowProjectResourceMonitor = true
#loginAttemptLimit = 5
#loginBlockTime = 180
allowManualImageNameForSession = true
debug = false
hideAgents = false
enable2FA = true
force2FA = false
singleSignOnVendors = "openid"
enableModelStore = true
allowSignupWithoutConfirmation = true
alwaysEnqueueComputeSession = true
# directoryBasedUsage = true
enableContainerCommit = true
allowCustomResourceAllocation = true
enableExtendLoginSession = false
enableLLMPlayground = false
enableImportFromHuggingFace = true
showKernelList = true
enableInteractiveLoginAccountSwitch = false

[wsproxy]
proxyURL = "http://127.0.0.1:5050"
#proxyBaseURL = ""
disableCertCheck = false


[menu]
# blocklist = "ai-agent"
# inactivelist = "ai-agent,model-store,serving,job,data"

[resources]
openPortToPublic = false
allowNonAuthTCP = true
allowPreferredPort = false
maxCPUCoresPerContainer = 32
maxMemoryPerContainer = 64
maxCUDADevicesPerContainer = 16
maxCUDASharesPerContainer = 8
maxROCMDevicesPerContainer = 10
maxTPUDevicesPerContainer = 8
maxIPUDevicesPerContainer = 64
maxATOMDevicesPerContainer = 8
maxWarboyDevicesPerContainer = 8
maxGaudi2DevicesPerContainer = 3
maxShmPerContainer = 256.0
maxFileUploadSize = 4294967296

[environments]
#allowlist = ""
showNonInstalledImages = true

# [server]
# webServerURL = "http://127.0.0.1:8090"

[plugin]
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
# page = "privacy-policy,terms-of-service"
# page = "tutorial-hira-plugin"
# page = "ai-train-support"
#
#[license]
#This field is generated by console-server.

# [pipeline]
# endpoint = "http://google.com"
# frontendEndpoint = "http://daum.net"
