supergraph:
  listen: 0.0.0.0:4000

include_subgraph_errors:
  all: true

headers:
  all:
    request:
      - propagate:
          matching: ".*"
      - insert:
          name: "host"
          value: "localhost:8091"
      - insert:
          name: "X-Forwarded-URL"
          # NOTE: When the host port and container port differ in Docker Compose, you must use the host port 
          # NOTE: Trailing slash is required
          value: "http://127.0.0.1:4000/" 
