name: timeline-check

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  merge_group:

jobs:
  pr-number-assign:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip:changelog') && github.event.pull_request.number != null }}
    uses: ./.github/workflows/pr-number-assign.yml

  towncrier:
    needs: [pr-number-assign]
    runs-on: ubuntu-latest
    steps:
    - name: Get PR's fetch depth
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}
        sparse-checkout: changes
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U towncrier~=22.12
    - name: Check existence of news fragment
      run: |
        # Check if the PR has a news fragment
        git fetch --depth=1 origin "${BASE_BRANCH}"
        NEWS_FRAGMENTS=$(git diff --name-only origin/${BASE_BRANCH} -- changes/)
        for change in $NEWS_FRAGMENTS; do
          if [ $(basename $change | cut -d'.' -f1) != $PR_NUMBER ]; then
            echo "$change is not valid news fragment file name"
            echo "The news fragment file name must be $PR_NUMBER"
            exit 1
          fi
        done
        python -m towncrier.check --compare-with=origin/${BASE_BRANCH}
      env:
        BASE_BRANCH: ${{ github.base_ref }}
