name: timeline-check

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  merge_group:

jobs:
  pr-number-assign:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip:changelog') && github.event.pull_request.number != null }}
    uses: ./.github/workflows/pr-number-assign.yml
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}

  towncrier:
    needs: [pr-number-assign]
    runs-on: ubuntu-latest
    steps:
    - name: Get PR's fetch depth
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}
        sparse-checkout: changes
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U towncrier~=22.12
    - name: Check existence of news fragment
      run: |
        BASE_COMMIT=$(git rev-list --first-parent --max-parents=0 --max-count=1 HEAD)
        BASE_TIMESTAMP=$(git log --format=%ct "${BASE_COMMIT}")
        git fetch --no-tags --shallow-since "${BASE_TIMESTAMP}" origin "${BASE_REF}"
        python -m towncrier.check --compare-with=origin/${BASE_REF}
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
