name: timeline-check

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  merge_group:

jobs:
  pr-number-assign:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip:changelog') }}
    uses: ./.github/workflows/pr-number-assign.yml

  towncrier:
    needs: [pr-number-assign]
    runs-on: ubuntu-latest
    steps:
    - name: Sparse-checkout
      uses: lablup/sparse-checkout@v1
      with:
        patterns: |
          changes
          scripts
          packages
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U towncrier~=21.9
    - name: Check existence of news fragment
      run: |
        # Check if the PR has a news fragment
        NEWS_FRAGMENTS=$(git diff --name-only origin/${BASE_BRANCH}...HEAD -- changes/)
        for change in $NEWS_FRAGMENTS; do
          if [ $(basename $change | cut -d'.' -f1) != $PR_NUMBER ]; then
            echo "$change is not valid news fragment file name"
            echo "The news fragment file name must be $PR_NUMBER"
            exit 1
          fi
        done
        git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
        python -m towncrier.check --compare-with=origin/${BASE_BRANCH}
      env:
        BASE_BRANCH: ${{ github.base_ref }}
        PR_NUMBER: ${{ github.event.number }}
